import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';

self.skipWaiting();
clientsClaim();

cleanupOutdatedCaches();

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Existing notification logic
let timeoutIds = [];
const dayMap = { 'Senin': 1, 'Selasa': 2, 'Rabu': 3, 'Kamis': 4, 'Jumat': 5, 'Sabtu': 6, 'Minggu': 0 };

function showNotification(item) {
    const className = item.className || item.class_id;
    self.registration.showNotification('Pengingat Kelas: ' + item.subject, {
        body: 'Kelas ' + className + ' akan dimulai pada pukul ' + item.start_time + '.',
        icon: '/logo.svg', // Use new SVG logo for notifications
        requireInteraction: true,
        tag: item.id,
    });
}

function scheduleNotifications(schedule) {
    clearScheduledNotifications();
    const now = new Date();
    const todayIndex = now.getDay();
    const upcomingClasses = schedule.filter(item => {
        if (dayMap[item.day] !== todayIndex) return false;
        const [hours, minutes] = item.start_time.split(':');
        const classTime = new Date();
        classTime.setHours(parseInt(hours, 10), parseInt(minutes, 10), 0, 0);
        return classTime > now;
    });
    upcomingClasses.forEach(item => {
        const [hours, minutes] = item.start_time.split(':');
        const classTime = new Date();
        classTime.setHours(parseInt(hours, 10), parseInt(minutes, 10), 0, 0);
        // Remind 5 minutes before
        const notificationTime = new Date(classTime.getTime() - 5 * 60 * 1000);
        if (notificationTime > now) {
            const delay = notificationTime.getTime() - now.getTime();
            const id = setTimeout(() => {
                showNotification(item);
            }, delay);
            timeoutIds.push(id);
        }
    });
}

function clearScheduledNotifications() {
    timeoutIds.forEach(clearTimeout);
    timeoutIds = [];
}

self.addEventListener('message', (event) => {
    if (event.data) {
        if (event.data.type === 'SCHEDULE_UPDATED') {
            scheduleNotifications(event.data.payload);
        } else if (event.data.type === 'CLEAR_SCHEDULE') {
            clearScheduledNotifications();
        }
    }
});
