import { cleanupOutdatedCaches, precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst, NetworkOnly } from 'workbox-strategies';
import { BackgroundSyncPlugin } from 'workbox-background-sync';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

// Do NOT call self.skipWaiting() unconditionally on load. This was causing forced mid-session
// reloads whenever a new Service Worker was deployed (e.g. while a teacher
// was saving grades). The new SW will now wait until the user explicitly
// clicks "Perbarui" on the update banner, or all tabs are closed naturally.
clientsClaim();

// Listen for message from update banner to skip waiting on demand
self.addEventListener('message', (event) => {
    if (event.data && (event.data.type === 'SKIP_WAITING' || event.data === 'skipWaiting')) {
        self.skipWaiting();
    }
});

cleanupOutdatedCaches();

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// ============================================
// SPA NAVIGATION FALLBACK
// ============================================
// This allows the app to work offline when a user navigates to /dashboard, /absensi, etc.
try {
    const handler = createHandlerBoundToURL('/index.html');
    const navigationRoute = new NavigationRoute(handler, {
        // Allow API calls to pass through normally
        denylist: [
            new RegExp('^/api/'),
            new RegExp('/[^/]+\\.[^/]+$'), // exclude files like /logo.png
        ],
    });
    registerRoute(navigationRoute);
} catch (e) {
    console.error('Failed to create NavigationRoute', e);
}


// Cache hashed Vite assets only after they are requested. This preserves repeat
// visit performance without forcing every lazy route/export chunk onto first load.
registerRoute(
    ({ url, request }) =>
        url.origin === self.location.origin &&
        ['script', 'style', 'font', 'worker'].includes(request.destination),
    new CacheFirst({
        cacheName: 'app-static-runtime',
        plugins: [
            {
                cacheWillUpdate: async ({ request, response }) => {
                    const contentType = response.headers.get('content-type') || '';
                    const destinations = ['script', 'style', 'font', 'worker'];
                    if (destinations.includes(request.destination) && contentType.includes('text/html')) {
                        return null;
                    }
                    return response;
                }
            },
            new CacheableResponsePlugin({
                statuses: [0, 200],
            }),
            new ExpirationPlugin({
                maxEntries: 80,
                maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
            }),
        ],
    })
);


// ============================================
// OFFLINE MUTATION QUEUE (BACKGROUND SYNC)
// ============================================
// Intercepts failed POST/PATCH/PUT/DELETE requests to Supabase and saves them to IndexedDB.
// When internet is restored, the Service Worker automatically retries these requests.
const bgSyncPlugin = new BackgroundSyncPlugin('supabase-mutations-queue', {
    maxRetentionTime: 24 * 60, // Retry for max of 24 Hours (specified in minutes)
});

registerRoute(
    ({ url, request }) =>
        url.hostname.includes('supabase') &&
        ['POST', 'PATCH', 'PUT', 'DELETE'].includes(request.method),
    new NetworkOnly({
        plugins: [bgSyncPlugin],
    })
);

// Cache Supabase API responses (NetworkFirst - try network, fallback to cache)
// Only cache unauthenticated GET requests to avoid serving user-specific data
// from a previous session. Auth endpoints are always excluded.
registerRoute(
    ({ url, request }) =>
        url.hostname.includes('supabase') &&
        request.method === 'GET' &&
        !url.pathname.includes('/auth/') &&
        !request.headers.has('authorization'),
    new NetworkFirst({
        cacheName: 'supabase-api-cache',
        plugins: [
            new CacheableResponsePlugin({
                statuses: [0, 200],
            }),
            new ExpirationPlugin({
                maxEntries: 100,
                maxAgeSeconds: 60 * 60 * 24, // 24 hours
            }),
        ],
        networkTimeoutSeconds: 10, // Fallback to cache after 10 seconds
    })
);

// NOTE: Google Fonts CDN cache routes removed — fonts are self-hosted via
// @fontsource (src/styles/fonts.css) and precached as assets/fonts/*.woff2,
// so the CDN origins are never requested and these routes were dead code.
// Clean up the old CDN caches left behind by previous service worker versions.
self.addEventListener('activate', (event) => {
    event.waitUntil(
        Promise.all([
            caches.delete('google-fonts-stylesheets'),
            caches.delete('google-fonts-webfonts'),
        ])
    );
});

// Cache images
registerRoute(
    ({ request }) => request.destination === 'image',
    new CacheFirst({
        cacheName: 'images-cache',
        plugins: [
            new CacheableResponsePlugin({
                statuses: [0, 200],
            }),
            new ExpirationPlugin({
                maxEntries: 60,
                maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
            }),
        ],
    })
);

// ============================================
// WEB PUSH NOTIFICATION HANDLERS
// ============================================
// Notifications are now driven by the Supabase `dispatch-push` Edge Function
// which sends push messages via the browser's Push Service. The Service Worker
// is woken up by the `push` event - this works even when the PWA is closed or
// the device screen is off, unlike the previous in-SW setTimeout approach.

self.addEventListener('push', (event) => {
    let payload = {
        title: 'MI Al Irsyad Kota Madiun',
        body: 'Anda memiliki notifikasi baru.',
        icon: '/icons/icon-192x192.png',
        badge: '/icons/badge-72x72.png',
        tag: undefined,
        data: {},
        requireInteraction: false,
        actions: [],
    };

    if (event.data) {
        try {
            const parsed = event.data.json();
            payload = {
                ...payload,
                ...parsed,
                data: parsed.data ?? {},
            };
        } catch (err) {
            // Fallback to text body if not valid JSON
            const text = event.data.text();
            if (text) payload.body = text;
        }
    }

    const options = {
        body: payload.body,
        icon: payload.icon,
        badge: payload.badge,
        tag: payload.tag,
        data: payload.data,
        requireInteraction: payload.requireInteraction,
        actions: payload.actions,
        vibrate: [200, 100, 200],
        timestamp: Date.now(),
    };

    event.waitUntil(
        self.registration.showNotification(payload.title, options)
    );
});

self.addEventListener('notificationclick', (event) => {
    event.notification.close();

    const data = event.notification.data || {};
    const targetUrl = typeof data.url === 'string' ? data.url : '/';

    if (event.action === 'dismiss') {
        return;
    }

    event.waitUntil(
        self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
            for (const client of clientList) {
                if ('focus' in client) {
                    client.postMessage({ type: 'PUSH_CLICK', payload: data });
                    return client.focus();
                }
            }
            if (self.clients.openWindow) {
                return self.clients.openWindow(targetUrl);
            }
        })
    );
});

self.addEventListener('pushsubscriptionchange', (event) => {
    // The push subscription expired or rotated. The client will re-subscribe
    // on next visit; we just notify any open clients to trigger that flow.
    event.waitUntil(
        self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clients) => {
            clients.forEach((client) => {
                client.postMessage({
                    type: 'PUSH_SUBSCRIPTION_EXPIRED',
                    payload: { oldEndpoint: event.oldSubscription?.endpoint },
                });
            });
        })
    );
});

async function clearSupabaseCache() {
    await caches.delete('supabase-api-cache');
}

// ============================================
// BACKGROUND SYNC
// ============================================

const SYNC_QUEUE_DB = 'sync-queue-db';
const SYNC_QUEUE_STORE = 'pending-requests';

// Initialize IndexedDB for background sync queue
async function openSyncDB() {
    return new Promise((resolve, reject) => {
        const request = indexedDB.open(SYNC_QUEUE_DB, 1);

        request.onerror = () => reject(request.error);
        request.onsuccess = () => resolve(request.result);

        request.onupgradeneeded = (event) => {
            const db = event.target.result;
            if (!db.objectStoreNames.contains(SYNC_QUEUE_STORE)) {
                db.createObjectStore(SYNC_QUEUE_STORE, { keyPath: 'id', autoIncrement: true });
            }
        };
    });
}

// Add failed request to sync queue
async function addToSyncQueue(request, data) {
    const db = await openSyncDB();
    const tx = db.transaction(SYNC_QUEUE_STORE, 'readwrite');
    const store = tx.objectStore(SYNC_QUEUE_STORE);

    const item = {
        url: request.url,
        method: request.method,
        headers: [...request.headers.entries()],
        body: data,
        timestamp: Date.now(),
    };

    await store.add(item);
}

// Get all pending sync items
async function getSyncQueue() {
    const db = await openSyncDB();
    const tx = db.transaction(SYNC_QUEUE_STORE, 'readonly');
    const store = tx.objectStore(SYNC_QUEUE_STORE);

    return new Promise((resolve, reject) => {
        const request = store.getAll();
        request.onsuccess = () => resolve(request.result);
        request.onerror = () => reject(request.error);
    });
}

// Remove item from sync queue
async function removeFromSyncQueue(id) {
    const db = await openSyncDB();
    const tx = db.transaction(SYNC_QUEUE_STORE, 'readwrite');
    const store = tx.objectStore(SYNC_QUEUE_STORE);
    await store.delete(id);
}

// Handle background sync
async function handleBackgroundSync() {
    try {
        const queue = await getSyncQueue();

        for (const item of queue) {
            try {
                const headers = new Headers(item.headers);
                const response = await fetch(item.url, {
                    method: item.method,
                    headers,
                    body: item.body ? JSON.stringify(item.body) : undefined,
                });

                if (response.ok) {
                    await removeFromSyncQueue(item.id);

                    // Notify clients of successful sync
                    const clients = await self.clients.matchAll();
                    clients.forEach(client => {
                        client.postMessage({
                            type: 'SYNC_SUCCESS',
                            payload: { id: item.id, url: item.url }
                        });
                    });
                }
            } catch (error) {
                console.error('Sync failed for item:', item.id, error);
            }
        }
    } catch (error) {
        console.error('Background sync error:', error);
    }
}

// Register sync event handler
self.addEventListener('sync', (event) => {
    if (event.tag === 'sync-data') {
        event.waitUntil(handleBackgroundSync());
    } else if (event.tag === 'offline-sync') {
        // Notify clients to trigger their offline sync implementation
        event.waitUntil(
            self.clients.matchAll().then(clients => {
                clients.forEach(client => client.postMessage({ type: 'TRIGGER_SYNC' }));
            })
        );
    }
});

// Periodic background sync (requires registration in client)
self.addEventListener('periodicsync', (event) => {
    if (event.tag === 'periodic-sync-data') {
        event.waitUntil(handleBackgroundSync());
    } else if (event.tag === 'periodic-offline-sync') {
        event.waitUntil(
            self.clients.matchAll().then(clients => {
                clients.forEach(client => client.postMessage({ type: 'TRIGGER_SYNC' }));
            })
        );
    }
});

// ============================================
// MESSAGE HANDLERS
// ============================================

self.addEventListener('message', (event) => {
    if (event.data) {
        if (event.data.type === 'SKIP_WAITING') {
            self.skipWaiting();
        } else if (event.data.type === 'CLEAR_SUPABASE_CACHE') {
            event.waitUntil(clearSupabaseCache());
        } else if (event.data.type === 'QUEUE_SYNC_REQUEST') {
            event.waitUntil(addToSyncQueue(event.data.request, event.data.data));
        } else if (event.data.type === 'TRIGGER_SYNC') {
            event.waitUntil(handleBackgroundSync());
        }
        // SCHEDULE_UPDATED, CLEAR_SCHEDULE, TASKS_UPDATED are deprecated -
        // scheduling now happens server-side via the dispatch-push Edge Function.
    }
});
